server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}

spring:
  profiles:
    active: dev
    group:
      dev:
      - local
      - datasource
      local:
       - local
       - datasource


