server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}

spring:
  profiles:
    group:
      dev:
      - local
      - datasource
      - auth
      local:
       - local
       - datasource
       - auth

