server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}

spring:
  profiles:
    active: dev
    group:
      dev:
      - local
      - datasource
      - auth
      local:
       - local
       - datasource
       - auth
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}
