logging:
  level:
    root: INFO
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG

spring:
  config:
    activate:
      on-profile: "deploy"
#    import: "aws-secretsmanager:/secret/odos-db-dev"

#  cloud:
#    aws:
#      region:
#        static: "ap-northeast-2"
#      credentials:
#        access-key: ${AWS_ACCESS_KEY_ID}
#        secret-key: ${AWS_SECRET_ACCESS_KEY}

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${host}:${port}/${db}
    username: ${username}
    password: ${password}

  graphql:
    graphiql:
      enabled: true

server:
  port: ${server_port}