name: Deploy to Elastic Beanstalk
on:
  push:
    branches: [ "dev" ]
permissions:
  id-token: write      # OIDC
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) AWS OIDC 연동(권장, 액세스 키 불필요)
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::406816180769:role/GitHubOIDCRole
          aws-region: ap-northeast-2

      # 2) 빌드 · 테스트 · 도커 이미지 태깅
      - name: Build & zip
        run: |
          zip -r app.zip .
      # 3) EB 배포
      - uses: einaregilsson/beanstalk-deploy@v22
        with:
          application_name: 1d1s-test
          environment_name: 1d1s-test-env
          version_label: ${{ github.sha }}
          region: ap-northeast-2
          deployment_package: app.zip
