name: Deploy to Elastic Beanstalk
on:
  push:
    branches: [ "dev" ]
permissions:
  id-token: write      # OIDC
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) AWS OIDC 연동(권장, 액세스 키 불필요)
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::406816180769:role/GitHubOIDCRole
          aws-region: ap-northeast-2

      # 2) 빌드 · 테스트 · 도커 이미지 태깅
      - name: Build & zip
        run: |
          zip -r app.zip .
      # 3) EB 배포
      - uses: einaregilsson/beanstalk-deploy@v22   # v22 그대로 사용 가능
        with:
          aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ env.AWS_SESSION_TOKEN }}   # 중요! OIDC면 꼭 함께 넘김
          application_name: 1d1s-test
          environment_name: 1d1s-test-env
          version_label: ${{ github.sha }}
          region: ap-northeast-2
          deployment_package: app.zip